package com.example.wallofshame

import android.content.Context
import android.content.Intent
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.wrapContentSize
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.core.content.ContextCompat.startActivity
import com.example.wallofshame.ui.theme.WallofShameTheme

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        val context = this
        setContent {
            WallofShameTheme {

                    DisclaimerScreen(modifier = Modifier, context)

            }
        }
    }
}

@Composable
fun DisclaimerScreen(modifier: Modifier = Modifier.fillMaxWidth(), context:Context) {
    Column(modifier = Modifier
        .padding(all = 16.dp)
        .padding(top = 48.dp)
        .wrapContentSize()
        .fillMaxWidth(), verticalArrangement = Arrangement.Top, horizontalAlignment = Alignment.CenterHorizontally) {

    Text(text = "DISCLAIMER",
        fontWeight = FontWeight.Bold,
        fontSize = 44.sp,
        modifier = Modifier)
    Spacer(modifier = Modifier.height(28.dp))
    Text(text = """This app is intended to provide a platform for users to share their experiences and opinions about government and private organizations. The ratings and reviews generated are based on a combination of public voting and algorithmic analysis.

It is explicitly stated that the app and its developers do not intend to defame any organization. Any negative feedback or low ratings reflect the opinions of the public and are not a personal attack or accusation.

The content generated by the app may contain opinions that some users find offensive or upsetting. Users who are sensitive to such content are advised not to use this app.

By using this app, users agree to hold the app developers harmless from any and all claims, damages, or liabilities arising from the use of the app or its content.""",
        fontSize = 16.sp,
        textAlign = TextAlign.Justify)
        Spacer(modifier = Modifier.height(28.dp))
        Button(onClick = {val intent = (Intent(context, CountrySelect::class.java))
            startActivity(context,intent,null) },
            modifier = Modifier,
            colors = ButtonDefaults.buttonColors(
            containerColor = Color.Black,
            contentColor = Color.White,
            ))
        {
            Text(text = "Next")
        }

    }
}

